### ISSUE TITLE
TVRemotePlus 相当の機能を提供する

### ISSUE THREAD

**Issue by SlashNephy** [SlashNephy/saya#10]
- [x] ライブ再生機能 w/ 実況
- [x] 録画番組再生機能 w/ 実況
- [ ] ファイル再生機能 (EPGStation から管理を外れた TS ファイルを再生可能にする)

**Comment by ohmsa** [comment]
管理を外れたmp4を、例えばあらかじめ指定したファイル名から取得してコメント取得というのは出来ませんでしょうか。

**Comment by SlashNephy** [comment]
ご意見ありがとうございます！

TS ファイルには EPG 情報が残っているため番組の開始時間に合わせてコメントの取得が行なえますが、mp4 ファイルには対応していません。
ファイル名のフォーマット (例えば https://github.com/l3tnun/EPGStation/blob/master/doc/conf-manual.md#recordedformat) を指定してファイル名から番組の開始時間を推測することはできると思います。
番組の長さも ffprobe あたりで取得できると思います。
検討してみます！

**Comment by ohmsa** [comment]
ファイル名からおおよその時刻とチャンネルを取得し、コメントの時刻を秒単位で調整できると良さそうです。

また、ニコ実の文化でAパート始まると「A」と、Bパート始まると「B」とコメントが流れるので、おおよそのCMスキップ的なことをコメントから推測できるかもしれません。（B単体のコメントが複数あって映像に暗転処理がある等）

**Comment by SlashNephy** [comment]
おもしろいアイディアありがとうございます💡

CM スキップの着想はありましたが保留にしていました。
はじめは CM 検出ツールとして有名な Comskip の利用を考えていましたが、実行コストが高いことから断念しました。
コメントからパートを判別する方法なら手軽に実装できそうです。

**Comment by ohmsa** [comment]
例えばWebUI側から「ここからOP、ここからAパート、ここからBパート」みたいなチャプターマークを付けてそれを「動画の開始（TSのEPGまたはmp4の名前から時刻を取得）から何秒後、何秒後、」とテキストに書きだし（この時点では自分用）、同じチャネルの同じ番組には自動適用（番組毎にCMの長さは大して変わらないため）して再生、最終的には利用者間で共有して精度を高める……なんてできるとCMスキップできそうですね。

後々（ある程度CM情報が貯まったら）メニューから指定するとチャプターではなくffmpegでカットして容量を減らす、なんてことも出来そうですし。
