### ISSUE TITLE
インストールマニュアルについて

### ISSUE THREAD

**Issue by ohmsa** [SlashNephy/saya#22]
すみません、いきなりこういうことを言うのも不躾ではありますが……

- Elainaとsayaがあり、どうもニコニコ実況を載せられるらしい
- Dockerで入れるらしい
というのはわかるのですが、インストール方法や前提となるソフト（Docker等）が少々わかりづらいです。

Mirakurunの表記を参考にインストールマニュアルさえ書いていただければ、こちらで動かしてみてマニュアル的なものがかけるかもしれません。

見た感じ面白そうで、将来性もありそうなソフトなので、使ってみたいです。
インストールマニュアルについてご一考いただけますでしょうか。

**Comment by SlashNephy** [comment]
コメントありがとうございます！

バージョン 1.0.0 リリースまでにドキュメントの準備等を終わらせたいと思っています。
加えて、いきなり Docker というのもハードルが高いと思う方もいると思うので
単独で実行できるバイナリの配布などを行ったり、環境変数ではない方法で（コマンドラインやファイルから）設定を変える機能などを実装したりとユーザフレンドリーにしたいと思っています。

**Comment by ohmsa** [comment]
先にDockerでのインストール出来れば私やほかの人が書けるかもしれないので、
「Dockerのこの画面にこう打ち込んだらインストール出来てこう打ち込んだらこのアドレス見てみ」
みたいな数行追記してもらえれば……

現状EPGSTATIONで
・番組表取得・表示
・録画予約
・録画実行
・エンコード
・動画登録・公開
が出来てるので、「EPGSTATIONと比べて何が出来るか」は知りたい気もします。
・リアルタイム、動画視聴時にコメ載せられる
はわかりますが……。

EPGStationで出来てなくてあると便利そうなのは
・サーバー管理機能（Mirakurun自体の再起動やキャッシュ削除、録画予約とエンコードがない時間帯の本体再起動等）
・節電機能（数時間録画がない時間帯は次の録画時間の30分前までスリープさせる等）
・エラー通知機能（定期的に1秒だけ録画してみて動画が取れなかったりするとメールを投げる）
・エンコード後任意命令発行（エンコード時だけPowercfgでCPUクロックを上げ、終わると下げる等）
・新番組検索
・任意の動画公開（フォルダ名とファイル名等から自動DB作成）
・ドロップの判定（ドロップ検知したらその瞬間のサムネを取ってCM中か本編か、酷いかどうか等を判定できる）
あたりでしょうか。

よくわからないので難易度高そうなところはありますが、いくつかは「特定タイミングでバッチファイルかシェルスクリプトを走らせる機能」があれば条件付けとバッチファイルの準備で行けそうです。バッチファイルの作成くらいならお役に立てそうです。

**Comment by SlashNephy** [comment]
dev ブランチの方で [README](https://github.com/SlashNephy/saya/blob/dev/README.md) を更新してみました。が、Docker に馴染みがない人には難しく感じられると思います。

ところで saya は現在 EPGStation に従属したアプリケーションとして開発しています。
しかし開発初期は Chinachu を使用していた都合で、予約・録画機能まで saya でオーバーホールしたいと思っていました。それは Close された過去の Issue https://github.com/SlashNephy/saya/issues/1 に名残があります。
ところが新規のコードベースでゼロから予約・録画機能まで担当するのは、開発が追いつかなかったりプロジェクトが肥大化してしまったりなどの問題が考えられ、視聴環境のオーバーホールに的を絞るように方針を転換しました。
先月の EPGStation v2 のリリースに合わせ、v0.0.1 リリースの saya から予約・録画機能の基礎が削除された流れです。

そのため、saya 自体では予約・録画関連の機能は実装しません。さらに既に EPGStation が有する API を再実装しません。その代わり、Web ベースのプレイヤーを拡張する API を多く実装する予定で、実況コメの配信もその1つです。
あくまでも EPGStation が動作している環境で視聴体験を拡充するためのプロジェクトなので、差異はそのあたりです。

[TVRemotePlus](https://github.com/tsukumijima/TVRemotePlus) さんが Linux 環境で動作するぐらいのイメージでよいかと思われます。saya は Mirakurun or mirakc で動作するため、BonDriver が不要になっています。

という方針なので、申し訳ありませんがご提示いただいた機能は実装予定にありません。

> ・エンコード後任意命令発行（エンコード時だけPowercfgでCPUクロックを上げ、終わると下げる等）

こちらは EPGStation のエンコードスクリプトで対応できそうです。(https://github.com/l3tnun/EPGStation/blob/master/config/enc3.js)

**Comment by ohmsa** [comment]
承知いたしました。ありがとうございます。
