### ISSUE TITLE
放送中の番組の Annict 情報を取得

### ISSUE THREAD

**Issue by SlashNephy** [SlashNephy/saya#8]

**Comment by iam-takagi** [comment]
annict-kt 1.1.3 移行へのお願いします～

**Comment by iam-takagi** [comment]
annict-kt 1.1.3 移行お願いします～

**Comment by r130919** [comment]
annict-kt 1.1.3 移行お願いします～
https://github.com/iam-takagi/annict-kt

**Comment by SlashNephy** [comment]
わざわざありがとうございます。更新しました！

**Comment by r130919** [comment]
度々申し訳ございません。
不具合修正のため新バージョン 2.1.0 リリースしました
お手数をおかけしますがお願いします！

**Comment by SlashNephy** [comment]
またしてもありがとうございます。本年もよろしくおねがいします！

**Comment by r130919** [comment]
こちらこそよろしくお願いします！
